### ISSUE TITLE
inavlid link

### ISSUE THREAD

**Issue by tessus** [chenlijun99/autoanki#1]
https://github.com/chenlijun99/autoanki/blob/fc025eb83ae2e4511d00a7cd83e86de970fd7e3f/packages/joplin-plugin/src/manifest.json#L9

**Comment by chenlijun99** [comment]
Thank you for noticing this problem!

**Comment by codeasashu** [comment]
The url is giving 404. Please reopen the issue

**Comment by chenlijun99** [comment]
Hi. I'm sorry, but the joplin has been deleted since it has never been in a usable shape and I have no plans to work on it in the forseable future. ~~Perhaps we should ask the folks that maintain https://github.com/joplin/plugins to remove the "Joplin Anki Sync" entry from the table~~. https://github.com/joplin/plugins collects the list of Joplin plugins from npmjs based on some filtering criteria. I removed the `joplin-plugin-anki-sync` package from npm. Hope that this will avoid further confusion in future.
